version: "3.9"

x-environment: &environment-shared
  POSTGRES_DB: postgres
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: postgres
  SECRET_KEY: ${SECRET_KEY}
  SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
  SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_SECRET}

services:
  front:
    image: sermalenk/skypro-front:lesson_36
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: nosatenko/todo_list:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment: *environment-shared
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  migrations:
    image: nosatenko/todo_list:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment: *environment-shared
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate"

  postgres:
    image: postgres:13.0-alpine
    restart: always
    environment: *environment-shared
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: