# DATABASE_URL = "psql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_HOST = "${POSTGRES_HOST}"
SECRET_KEY = 'django-insecure-8-(s6kcw1h8sv_%@bg+j#(0*zllhq+@o39vgkqfypw=pyhfh8f'
